# Generated by Django 3.2 on 2022-02-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Вид продукта',
                'verbose_name_plural': 'Виды продуктов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.productkind')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
                'ordering': ['pk'],
            },
        ),
    ]
